# Generated by Django 4.0 on 2021-12-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='avatar',
        ),
    ]
